apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: prime
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 60
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: 0yukali0/mpi-prime
            imagePullPolicy: IfNotPresent
            name: mpi-launcher
            securityContext:
              runAsUser: 1000
            command:
            - mpirun
            args:
            - -n
            - "2"
            - /home/mpiuser/prime.exe
            resources:
              limits:
                cpu: 500m
                memory: 500Mi
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: 0yukali0/mpi-prime
            imagePullPolicy: IfNotPresent
            name: mpi-worker
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            resources:
              limits:
                cpu: 500m
                memory: 500Mi
